/**
 * Database schema types, enums, DTOs, and domain view models
 * for the HNU DASH web application.
 *
 * Directly mirrors the PostgreSQL/Supabase multi-tenant schema defined in
 * supabase/Attendance_System_Database_Documentation.docx.
 */

// ==========================================
// 1. PostgreSQL Enumeration Types
// ==========================================

/**
 * Governs platform-wide privileges.
 * 'admin' denotes a Faculty Adviser / Superadmin with global authority across all tenants.
 * 'student' is the default for all university students.
 */
export type GlobalSystemRole = 'student' | 'admin';

/**
 * Governs permissions scoped strictly within a specific organization/department.
 * - 'admin': Student Org Admin who can create events, assign scanners, and finalize attendance.
 * - 'officer': Organization officer who can be delegated scanner duties and has early call-times.
 * - 'student': Regular member/attendee of the organization.
 */
export type TenantMemberRole = 'student' | 'officer' | 'admin';

/**
 * Differentiates entry check-in from exit check-out checkpoints.
 */
export type AttendanceScanType = 'time_in' | 'time_out';

/**
 * The operational attendance status assigned to an individual scan record.
 */
export type AttendanceStatus = 'present' | 'late' | 'excused';

// ==========================================
// 2. Database Entity Models (Tables)
// ==========================================

/**
 * Stores master user identities, linking directly to Supabase Auth (auth.users)
 * while holding institutional metadata.
 */
export interface Profile {
  id: string; // UUID, PK -> auth.users.id
  student_id: string; // VARCHAR(50), Unique barcode/QR value (e.g. "21-1234-567")
  first_name: string; // VARCHAR(100)
  last_name: string; // VARCHAR(100)
  course: string; // Degree program code (e.g. 'BSIT', 'BSCS', 'BSN')
  year_level: number; // 1 to 5
  role: GlobalSystemRole; // Default 'student', 'admin' for advisers
  created_at: string; // ISO 8601 TIMESTAMPTZ
}

/**
 * Represents academic departments, college councils, and
 * co-curricular/extra-curricular student organizations.
 */
export interface Organization {
  id: string; // UUID, PK
  name: string; // VARCHAR(150), Full display name
  code: string; // VARCHAR(30), Unique acronym or tag (e.g. 'SYCOMP', 'CCS')
  description: string | null; // TEXT
  created_at: string; // ISO 8601 TIMESTAMPTZ
}

/**
 * Implements multi-tenant mapping between users and organizations
 * alongside their scoped RBAC roles.
 * Enforces UNIQUE(organization_id, user_id).
 */
export interface OrganizationMember {
  id: string; // UUID, PK
  organization_id: string; // REFERENCES organizations(id)
  user_id: string; // REFERENCES profiles(id)
  role: TenantMemberRole; // Scoped role ('admin', 'officer', 'student')
  created_at: string; // ISO 8601 TIMESTAMPTZ
}

/**
 * Maintains event schedules, time-window parameters, audience filters,
 * and differentiated fine structures for students and officers.
 */
export interface Event {
  id: string; // UUID, PK
  organization_id: string; // REFERENCES organizations(id)
  title: string; // VARCHAR(255)
  description: string | null; // TEXT
  location: string; // VARCHAR(255)
  event_start: string; // ISO 8601 TIMESTAMPTZ
  event_end: string; // ISO 8601 TIMESTAMPTZ

  // Attendee Time Windows
  attendance_in_start: string;
  attendance_in_end: string;
  attendance_out_start: string;
  attendance_out_end: string;

  // Officer Early Call-Time & Egress Windows
  officer_in_start: string;
  officer_in_end: string;
  officer_out_start: string;
  officer_out_end: string;

  // Fine Structures (PHP)
  fine_per_missed_scan_student: number; // DECIMAL(10,2), default 0.00
  fine_per_missed_scan_officer: number; // DECIMAL(10,2), default 0.00

  // Audience Filter (NULL denotes all members of the organization are eligible)
  target_year_levels: number[] | null;

  created_by: string; // REFERENCES profiles(id)
  created_at: string; // ISO 8601 TIMESTAMPTZ
}

/**
 * Delegates specific officers to act as live attendance scanners for a given event.
 * An officer cannot perform attendance scanning unless actively assigned here.
 * Enforces UNIQUE(event_id, user_id).
 */
export interface EventAssignedScanner {
  id: string; // UUID, PK
  event_id: string; // REFERENCES events(id)
  user_id: string; // REFERENCES profiles(id)
  assigned_at: string; // ISO 8601 TIMESTAMPTZ
}

/**
 * Captures immutable, point-in-time scanning transactions generated by mobile/web scanners.
 * Enforces UNIQUE(event_id, student_id, type).
 */
export interface AttendanceLog {
  id: string; // UUID, PK
  event_id: string; // REFERENCES events(id)
  student_id: string; // REFERENCES profiles(id)
  scanned_by: string; // REFERENCES profiles(id)
  type: AttendanceScanType; // 'time_in' | 'time_out'
  scanned_at: string; // Timestamp recorded at time of scan
  synced_at: string; // Authoritative PostgreSQL server timestamp
  status: AttendanceStatus; // 'present' | 'late' | 'excused'
}

// ==========================================
// 3. Application View Models & Joined DTOs
// ==========================================

/**
 * An organization joined with the current user's membership details.
 * Used in the sidebar "Your Organizations:" list.
 */
export interface UserOrganizationMembership {
  organization: Organization;
  member_role: TenantMemberRole;
  joined_at: string;
}

/**
 * An event bundled with the hosting organization's metadata
 * and scanner assignment stats.
 */
export interface EventWithDetails extends Event {
  organization: Pick<Organization, 'id' | 'name' | 'code'>;
  assigned_scanners_count?: number;
  total_attendees_count?: number;
}

/**
 * Computed student attendance status for a specific event.
 * Aggregates both time_in and time_out scan logs.
 */
export interface StudentAttendanceRecord {
  event: EventWithDetails;
  time_in_log: AttendanceLog | null;
  time_out_log: AttendanceLog | null;
  fine_amount: number; // Computed fine based on missed scans
  overall_status: 'completed' | 'partial' | 'missed' | 'excused';
}

/**
 * Granular capability permissions within an organization context.
 * Used by UI components instead of checking raw role strings.
 */
export interface OrgPermissions {
  canManageEvents: boolean;
  canAssignScanners: boolean;
  canReviewAttendance: boolean;
  canFinalizeEvent: boolean;
  canScanEvent: (eventId: string) => boolean;
}

/**
 * Event time-window input payload for creation and validation.
 */
export interface EventTimeWindows {
  event_start: string;
  event_end: string;
  attendance_in_start: string;
  attendance_in_end: string;
  attendance_out_start: string;
  attendance_out_end: string;
  officer_in_start: string;
  officer_in_end: string;
  officer_out_start: string;
  officer_out_end: string;
}

/**
 * Mock Persona model for development and role testing.
 */
export interface Persona {
  id: string;
  label: string;
  description: string;
  profile: Profile;
  memberships: UserOrganizationMembership[];
  assigned_event_ids: string[];
}
